import { NavigationItem } from './types';

export const NAVIGATION_REGISTRY: NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    section: 'Overview',
    priority: 0,
  },
  {
    id: 'queue',
    label: 'Queue Management',
    href: '/queue',
    section: 'Clinical',
    priority: 10,
    requiredRoles: ['clinic_staff', 'doctor', 'dentist', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'patient-records',
    label: 'Patient Records',
    href: '/records',
    section: 'Clinical',
    priority: 12,
    requiredRoles: ['doctor', 'dentist', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'medical-records',
    label: 'Medical Records',
    href: '/medical-records',
    section: 'Clinical',
    priority: 13,
    requiredRoles: ['doctor', 'dentist', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'vitals',
    label: 'Vital Signs',
    href: '/vitals',
    section: 'Clinical',
    priority: 20,
    requiredRoles: ['nurse', 'doctor', 'admin', 'super_admin'],
  },
  {
    id: 'fbs',
    label: 'FBS Records',
    href: '/fbs',
    section: 'Clinical',
    priority: 21,
    requiredRoles: ['nurse', 'doctor', 'admin', 'super_admin'],
  },
  {
    id: 'prescriptions',
    label: 'Prescriptions',
    href: '/prescriptions',
    section: 'Clinical',
    priority: 22,
    requiredRoles: ['doctor', 'dentist', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'dental',
    label: 'Dental Records',
    href: '/dental',
    section: 'Clinical',
    priority: 23,
    requiredRoles: ['dentist', 'admin', 'super_admin'],
  },
  {
    id: 'odontogram',
    label: 'Odontogram',
    href: '/odontogram',
    section: 'Clinical',
    priority: 24,
    requiredRoles: ['dentist', 'admin', 'super_admin'],
  },
  {
    id: 'dispensing',
    label: 'Dispensing',
    href: '/dispensing',
    section: 'Pharmacy',
    priority: 30,
    requiredRoles: ['clinic_staff', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'dispensing-history',
    label: 'Dispensing History',
    href: '/dispensing/history',
    section: 'Pharmacy',
    priority: 31,
    requiredRoles: ['clinic_staff', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'medicines',
    label: 'Medicine Inventory',
    href: '/medicines',
    section: 'Pharmacy',
    priority: 31,
    requiredRoles: ['admin', 'super_admin'],
  },
  {
    id: 'referrals',
    label: 'Referrals',
    href: '/referrals',
    section: 'Documents',
    priority: 40,
    requiredRoles: ['doctor', 'dentist', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'follow-ups',
    label: 'Follow-ups',
    href: '/follow-ups',
    section: 'Documents',
    priority: 41,
    requiredRoles: ['doctor', 'dentist', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'clearances',
    label: 'Clearances',
    href: '/clearances',
    section: 'Documents',
    priority: 42,
    requiredRoles: ['doctor', 'dentist', 'clinic_staff', 'admin', 'super_admin'],
  },
  {
    id: 'incidents',
    label: 'Incident Reports',
    href: '/incidents',
    section: 'Documents',
    priority: 43,
    requiredRoles: ['doctor', 'dentist', 'nurse', 'admin', 'super_admin'],
  },
  {
    id: 'consent',
    label: 'Consent Management',
    href: '/consent',
    section: 'Documents',
    priority: 44,
    requiredRoles: ['clinic_staff', 'doctor', 'dentist', 'admin', 'super_admin'],
  },
  {
    id: 'documents',
    label: 'Documents',
    href: '/documents',
    section: 'Documents',
    priority: 45,
    requiredRoles: ['doctor', 'dentist', 'clinic_staff', 'admin', 'super_admin'],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    href: '/notifications',
    section: 'Overview',
    priority: 5,
  },
  {
    id: 'reports',
    label: 'Reports',
    href: '/reports',
    section: 'Analytics',
    priority: 50,
    requiredRoles: ['admin', 'super_admin'],
  },
  {
    id: 'inventory-report',
    label: 'Inventory Report',
    href: '/reports/inventory',
    section: 'Analytics',
    priority: 51,
    requiredRoles: ['clinic_staff', 'admin', 'super_admin'],
  },
  {
    id: 'admin-users',
    label: 'User Management',
    href: '/admin/users',
    section: 'Administration',
    priority: 60,
    requiredRoles: ['admin', 'super_admin'],
  },
  {
    id: 'admin-audit',
    label: 'Audit Logs',
    href: '/admin/audit',
    section: 'Administration',
    priority: 62,
    requiredRoles: ['admin', 'super_admin'],
  },
  {
    id: 'admin-library',
    label: 'Library Management',
    href: '/admin/library',
    section: 'Administration',
    priority: 63,
    requiredRoles: ['admin', 'super_admin'],
  },
  {
    id: 'carina',
    label: 'Carina AI',
    href: '#carina',
    section: 'AI',
    priority: 70,
  },
];
